import React, { createContext, useContext, useState, ReactNode } from 'react';
import { Language } from '../types';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const UI_TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    'getConsultation': 'Get Your Free Consultation',
    'freeConsultation': 'Free Consultation',
    'callNow': 'Call Now',
    'scheduleConsultation': 'Schedule Consultation',
    'viewDetails': 'View Details',
    'learnMore': 'Learn More',
    'overview': 'Overview',
    'relatedTopics': 'Related Scenarios & Topics',
    'needAssistance': 'Need immediate assistance?',
    'sendMessage': 'Send us a Message',
    'sendBtn': 'Send Message',
    'name': 'Name',
    'phone': 'Phone',
    'email': 'Email Address',
    'message': 'How can we help?',
    'messagePlaceholder': 'Please briefly describe your situation...',
    'successMessage': 'Thank you for contacting Son Law Firm. We will be in touch shortly.',
    'promiseTitle': 'Our Promise To You',
    'promiseText': 'There is no cost and no obligation to learn if we can help. If you retain us as your legal representative, you will pay no upfront fees or costs. Our fees come as a percentage of whatever compensation we obtain for you. In the unlikely event that we do not win compensation, you will pay no attorney fees whatsoever.',
    'personalNoteTitle': 'On a Personal Note',
    'education': 'Education',
    'admissions': 'Admissions',
    'attorneyProfile': 'Attorney Profile',
    'foundingPartner': 'Founding Partner',
    'contactUs': 'Contact Us',
    'call247': 'Call Us 24/7',
    'emailUs': 'Email Us',
    'visitOffice': 'Visit Office',
    'getDirections': 'Get Directions',
    'quickLinks': 'Quick Links',
    'practiceAreas': 'Practice Areas',
    'importantNotice': 'Important Notice',
    'noticeText': 'The information on this website is for general information purposes only. Nothing on this site should be taken as legal advice.',
    'allRightsReserved': 'Son Law Firm. All rights reserved.',
    'privacyPolicy': 'Privacy Policy',
    'termsOfService': 'Terms of Service',
    'backToTop': 'Back to Top',
    'writeReview': 'Write a Google review',
    'clientTestimonials': 'Client Testimonials',
    'ourExpertise': 'Our Expertise',
    'weCanHelp': 'We Can Help You',
    'expertiseIntro': 'The injury attorneys of Son Law Firm have obtained millions of dollars in financial compensation for clients who were seriously injured in auto accidents.',
    'areasOfPractice': 'Areas of Practice',
    'practiceIntro': 'Our firm focuses exclusively on personal injury law. This specialization allows us to maintain a deep expertise in the tactics insurance companies use to undervalue your claim.',
    'heroTitle': 'SON LAW FIRM',
    'heroSubtitle': 'Son Law Firm focuses on personal injury cases.',
    'heroText': 'If you have been injured in an accident due to no fault of your own, call us for a free consultation so we can help you determine your rights.',
    'heroHighlight': 'No upfront costs and no attorney’s fees unless we collect a settlement for you.',
    'scheduleFree': 'Schedule a free consultation',
    'dontHesitate': "Don't hesitate to reach out.",
    'committedText': 'We are committed to addressing your concerns. Contact us for a free consultation right now.'
  },
  ko: {
    'getConsultation': '무료 법률 상담 받기',
    'freeConsultation': '무료 상담',
    'callNow': '지금 전화하기',
    'scheduleConsultation': '상담 예약하기',
    'viewDetails': '자세히 보기',
    'learnMore': '더 알아보기',
    'overview': '개요',
    'relatedTopics': '관련 사례 및 주제',
    'needAssistance': '즉각적인 도움이 필요하신가요?',
    'sendMessage': '메시지 보내기',
    'sendBtn': '메시지 전송',
    'name': '이름',
    'phone': '전화번호',
    'email': '이메일 주소',
    'message': '무엇을 도와드릴까요?',
    'messagePlaceholder': '상황을 간략하게 설명해 주세요...',
    'successMessage': '손 법률 사무소에 연락해 주셔서 감사합니다. 곧 연락드리겠습니다.',
    'promiseTitle': '고객님을 위한 약속',
    'promiseText': '도움을 드릴 수 있는지 확인하는 데에는 비용이나 의무가 없습니다. 저희를 법적 대리인으로 선임하시더라도 선불 수수료나 비용은 없습니다. 수임료는 귀하를 위해 확보한 보상금의 일정 비율로 청구됩니다. 만약 보상금을 받지 못하는 경우, 변호사 수임료는 전혀 청구되지 않습니다.',
    'personalNoteTitle': '개인적인 이야기',
    'education': '학력',
    'admissions': '변호사 자격',
    'attorneyProfile': '변호사 프로필',
    'foundingPartner': '대표 변호사',
    'contactUs': '문의하기',
    'call247': '24/7 전화 상담',
    'emailUs': '이메일 문의',
    'visitOffice': '사무실 방문',
    'getDirections': '길 찾기',
    'quickLinks': '빠른 링크',
    'practiceAreas': '전문 분야',
    'importantNotice': '중요 공지',
    'noticeText': '이 웹사이트의 정보는 일반적인 정보 제공만을 목적으로 합니다. 이 사이트의 어떠한 내용도 법적 조언으로 간주되어서는 안 됩니다.',
    'allRightsReserved': '손 법률 사무소. All rights reserved.',
    'privacyPolicy': '개인정보 처리방침',
    'termsOfService': '이용 약관',
    'backToTop': '맨 위로',
    'writeReview': 'Google 리뷰 작성하기',
    'clientTestimonials': '고객 후기',
    'ourExpertise': '전문성',
    'weCanHelp': '도와드리겠습니다',
    'expertiseIntro': '손 법률 사무소의 상해 전문 변호사들은 자동차 사고로 심각한 부상을 입은 고객들을 위해 수백만 달러의 금융 보상을 받아냈습니다.',
    'areasOfPractice': '전문 분야',
    'practiceIntro': '저희 사무소는 오직 인신 상해법에만 집중합니다. 이러한 전문성을 바탕으로 보험사가 청구 금액을 낮추려는 전략에 깊이 있는 전문 지식으로 대응합니다.',
    'heroTitle': '손 법률 사무소',
    'heroSubtitle': '인신 상해 사건 전문',
    'heroText': '본인의 과실 없이 사고로 부상을 입으셨다면, 무료 상담을 통해 권리를 확인하실 수 있도록 전화해 주십시오.',
    'heroHighlight': '선불 비용이 없으며, 보상금을 받지 못하면 변호사 수임료도 없습니다.',
    'scheduleFree': '무료 상담 예약',
    'dontHesitate': '주저하지 말고 연락하세요.',
    'committedText': '고객님의 고민을 해결해 드리겠습니다. 지금 바로 무료 상담을 요청하세요.'
  },
  zh: {
    'getConsultation': '获取免费咨询',
    'freeConsultation': '免费咨询',
    'callNow': '立即致电',
    'scheduleConsultation': '预约咨询',
    'viewDetails': '查看详情',
    'learnMore': '了解更多',
    'overview': '概览',
    'relatedTopics': '相关案例与主题',
    'needAssistance': '需要立即协助？',
    'sendMessage': '发送信息',
    'sendBtn': '发送信息',
    'name': '姓名',
    'phone': '电话',
    'email': '电子邮箱',
    'message': '我们能为您做什么？',
    'messagePlaceholder': '请简要描述您的情况...',
    'successMessage': '感谢您联系孙律师事务所。我们会尽快与您联系。',
    'promiseTitle': '我们的承诺',
    'promiseText': '了解我们能否提供帮助无需任何费用或义务。如果您委托我们作为您的法律代表，您无需支付任何预付费用或成本。我们的费用将从为您争取的赔偿金中按比例提取。在极少数情况下，如果我们未能获得赔偿，您无需支付任何律师费。',
    'personalNoteTitle': '个人简介',
    'education': '教育背景',
    'admissions': '执业资格',
    'attorneyProfile': '律师简介',
    'foundingPartner': '创始合伙人',
    'contactUs': '联系我们',
    'call247': '24/7 致电',
    'emailUs': '发送邮件',
    'visitOffice': '拜访律所',
    'getDirections': '获取路线',
    'quickLinks': '快速链接',
    'practiceAreas': '业务领域',
    'importantNotice': '重要声明',
    'noticeText': '本网站上的信息仅供一般参考。本网站上的任何内容均不应被视为针对任何个案或情况的法律建议。',
    'allRightsReserved': '孙律师事务所. 保留所有权利.',
    'privacyPolicy': '隐私政策',
    'termsOfService': '服务条款',
    'backToTop': '返回顶部',
    'writeReview': '撰写 Google 评价',
    'clientTestimonials': '客户评价',
    'ourExpertise': '我们的专长',
    'weCanHelp': '我们可以为您提供帮助',
    'expertiseIntro': '孙律师事务所的人身伤害律师已为在车祸中受重伤的客户争取到了数百万美元的经济赔偿。',
    'areasOfPractice': '业务领域',
    'practiceIntro': '我们律所专注于人身伤害法。这种专业化使我们能够深入了解保险公司低估索赔的策略，并予以反击。',
    'heroTitle': '孙律师事务所',
    'heroSubtitle': '孙律师事务所专注于人身伤害案件。',
    'heroText': '如果您因非自身过错在事故中受伤，请致电我们进行免费咨询，我们将帮助您确定您的权利。',
    'heroHighlight': '无需预付费用，除非我们为您获得赔偿，否则不收取律师费。',
    'scheduleFree': '预约免费咨询',
    'dontHesitate': '请勿犹豫，立即联系。',
    'committedText': '我们致力于解决您的疑虑。立即联系我们进行免费咨询。'
  },
  es: {
    'getConsultation': 'Obtenga su Consulta Gratuita',
    'freeConsultation': 'Consulta Gratuita',
    'callNow': 'Llamar Ahora',
    'scheduleConsultation': 'Programar Consulta',
    'viewDetails': 'Ver Detalles',
    'learnMore': 'Aprender Más',
    'overview': 'Resumen',
    'relatedTopics': 'Temas Relacionados',
    'needAssistance': '¿Necesita asistencia inmediata?',
    'sendMessage': 'Envíenos un Mensaje',
    'sendBtn': 'Enviar Mensaje',
    'name': 'Nombre',
    'phone': 'Teléfono',
    'email': 'Correo Electrónico',
    'message': '¿Cómo podemos ayudarle?',
    'messagePlaceholder': 'Por favor describa brevemente su situación...',
    'successMessage': 'Gracias por contactar al Bufete Son. Nos pondremos en contacto pronto.',
    'promiseTitle': 'Nuestra Promesa',
    'promiseText': 'No hay costo ni obligación para saber si podemos ayudarle. Si nos contrata como su representante legal, no pagará tarifas ni costos por adelantado. Nuestros honorarios provienen de un porcentaje de cualquier compensación que obtengamos para usted. En el improbable caso de que no obtengamos compensación, no pagará honorarios de abogado en absoluto.',
    'personalNoteTitle': 'Nota Personal',
    'education': 'Educación',
    'admissions': 'Admisiones',
    'attorneyProfile': 'Perfil del Abogado',
    'foundingPartner': 'Socia Fundadora',
    'contactUs': 'Contáctenos',
    'call247': 'Llámenos 24/7',
    'emailUs': 'Envíenos un Email',
    'visitOffice': 'Visite la Oficina',
    'getDirections': 'Obtener Direcciones',
    'quickLinks': 'Enlaces Rápidos',
    'practiceAreas': 'Áreas de Práctica',
    'importantNotice': 'Aviso Importante',
    'noticeText': 'La información en este sitio web es solo para fines informativos generales. Nada en este sitio debe tomarse como asesoramiento legal.',
    'allRightsReserved': 'Bufete Son. Todos los derechos reservados.',
    'privacyPolicy': 'Política de Privacidad',
    'termsOfService': 'Términos de Servicio',
    'backToTop': 'Volver Arriba',
    'writeReview': 'Escribir reseña en Google',
    'clientTestimonials': 'Testimonios de Clientes',
    'ourExpertise': 'Nuestra Experiencia',
    'weCanHelp': 'Podemos Ayudarle',
    'expertiseIntro': 'Los abogados de lesiones del Bufete Son han obtenido millones de dólares en compensación financiera para clientes gravemente heridos en accidentes automovilísticos.',
    'areasOfPractice': 'Áreas de Práctica',
    'practiceIntro': 'Nuestra firma se enfoca exclusivamente en la ley de lesiones personales. Esta especialización nos permite mantener una profunda experiencia en las tácticas que usan las aseguradoras.',
    'heroTitle': 'BUFETE DE ABOGADOS SON',
    'heroSubtitle': 'El Bufete Son se especializa en casos de lesiones personales.',
    'heroText': 'Si ha resultado herido en un accidente sin culpa suya, llámenos para una consulta gratuita para que podamos ayudarle a determinar sus derechos.',
    'heroHighlight': 'Sin costos por adelantado y sin honorarios de abogados a menos que obtengamos un acuerdo para usted.',
    'scheduleFree': 'Programe una consulta gratuita',
    'dontHesitate': 'No dude en contactarnos.',
    'committedText': 'Estamos comprometidos a abordar sus inquietudes. Contáctenos para una consulta gratuita ahora mismo.'
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return UI_TRANSLATIONS[language][key] || UI_TRANSLATIONS['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};